/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as simpleZkpSol from "./simpleZKP.sol";
export { ElectionManager__factory } from "./ElectionManager__factory";
export { VoteCounter__factory } from "./VoteCounter__factory";
export { Voting__factory } from "./Voting__factory";
