/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as simpleZkpSol from "./simpleZKP.sol";
export type { simpleZkpSol };
export type { ElectionManager } from "./ElectionManager";
export type { VoteCounter } from "./VoteCounter";
export type { Voting } from "./Voting";
