/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface VoteCounterInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "finalizeCount"
      | "getCandidateVotes"
      | "getTotalVotes"
      | "isCountFinalized"
      | "isVoteRevealed"
      | "owner"
      | "renounceOwnership"
      | "results"
      | "revealVote"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CountingCompleted"
      | "OwnershipTransferred"
      | "VoteRevealed"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "finalizeCount",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getCandidateVotes",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalVotes",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isCountFinalized",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isVoteRevealed",
    values: [BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "results",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "revealVote",
    values: [BigNumberish, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "finalizeCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCandidateVotes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalVotes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isCountFinalized",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isVoteRevealed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "results", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "revealVote", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace CountingCompletedEvent {
  export type InputTuple = [
    electionId: BigNumberish,
    totalVotes: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    electionId: bigint,
    totalVotes: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    electionId: bigint;
    totalVotes: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VoteRevealedEvent {
  export type InputTuple = [
    electionId: BigNumberish,
    nullifierHash: BytesLike,
    candidateId: BigNumberish
  ];
  export type OutputTuple = [
    electionId: bigint,
    nullifierHash: string,
    candidateId: bigint
  ];
  export interface OutputObject {
    electionId: bigint;
    nullifierHash: string;
    candidateId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface VoteCounter extends BaseContract {
  connect(runner?: ContractRunner | null): VoteCounter;
  waitForDeployment(): Promise<this>;

  interface: VoteCounterInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  finalizeCount: TypedContractMethod<
    [_electionId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getCandidateVotes: TypedContractMethod<
    [_electionId: BigNumberish, _candidateId: BigNumberish],
    [bigint],
    "view"
  >;

  getTotalVotes: TypedContractMethod<
    [_electionId: BigNumberish],
    [bigint],
    "view"
  >;

  isCountFinalized: TypedContractMethod<
    [_electionId: BigNumberish],
    [boolean],
    "view"
  >;

  isVoteRevealed: TypedContractMethod<
    [_electionId: BigNumberish, _nullifierHash: BytesLike],
    [boolean],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  results: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, boolean, bigint, bigint] & {
        electionId: bigint;
        isCounted: boolean;
        totalVotes: bigint;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  revealVote: TypedContractMethod<
    [
      _electionId: BigNumberish,
      _nullifierHash: BytesLike,
      _candidateId: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "finalizeCount"
  ): TypedContractMethod<[_electionId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getCandidateVotes"
  ): TypedContractMethod<
    [_electionId: BigNumberish, _candidateId: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTotalVotes"
  ): TypedContractMethod<[_electionId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "isCountFinalized"
  ): TypedContractMethod<[_electionId: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "isVoteRevealed"
  ): TypedContractMethod<
    [_electionId: BigNumberish, _nullifierHash: BytesLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "results"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, boolean, bigint, bigint] & {
        electionId: bigint;
        isCounted: boolean;
        totalVotes: bigint;
        timestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "revealVote"
  ): TypedContractMethod<
    [
      _electionId: BigNumberish,
      _nullifierHash: BytesLike,
      _candidateId: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "CountingCompleted"
  ): TypedContractEvent<
    CountingCompletedEvent.InputTuple,
    CountingCompletedEvent.OutputTuple,
    CountingCompletedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "VoteRevealed"
  ): TypedContractEvent<
    VoteRevealedEvent.InputTuple,
    VoteRevealedEvent.OutputTuple,
    VoteRevealedEvent.OutputObject
  >;

  filters: {
    "CountingCompleted(uint256,uint256,uint256)": TypedContractEvent<
      CountingCompletedEvent.InputTuple,
      CountingCompletedEvent.OutputTuple,
      CountingCompletedEvent.OutputObject
    >;
    CountingCompleted: TypedContractEvent<
      CountingCompletedEvent.InputTuple,
      CountingCompletedEvent.OutputTuple,
      CountingCompletedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "VoteRevealed(uint256,bytes32,uint256)": TypedContractEvent<
      VoteRevealedEvent.InputTuple,
      VoteRevealedEvent.OutputTuple,
      VoteRevealedEvent.OutputObject
    >;
    VoteRevealed: TypedContractEvent<
      VoteRevealedEvent.InputTuple,
      VoteRevealedEvent.OutputTuple,
      VoteRevealedEvent.OutputObject
    >;
  };
}
